program: train.py
method: grid
metric:
  name: val/model_loss
  goal: minimize
parameters:
  config:
    value: 'config/adversarial.yaml'
  lambda_adversarial:
    values: [0.01, 0.1, 0.3]
  phi_probe_steps_per_model_update:
    values: [0.01, 0.1, 1, 5]
  max_iters:
    values: [2000, 10000]