program: train.py
method: grid  # You could also use 'random' or 'bayes'
metric:
  name: val/model_loss  # The metric to optimize (assuming this is what you track)
  goal: minimize
parameters:
  config:
    value: 'config/adversarial.yaml'  # Your base config
  lambda_adversarial:
    values: [0.01, 0.05, 0.1, 1.0]
  phi_probe_steps_per_model_update:
    values: [1, 5, 10, 30]
  max_iters:
    values: [10, 2000, 10000]